#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Colour

echo -e "${CYAN}========================================${NC}"
echo -e "${CYAN}  Student Attendance Tracker Bootstrapper${NC}"
echo -e "${CYAN}========================================${NC}"
echo ""

if [[ -z "$1" ]]; then
    read -rp "Enter a project identifier (e.g. cohort_2025): " PROJECT_INPUT
else
    PROJECT_INPUT="$1"
fi

if [[ -z "$PROJECT_INPUT" ]]; then
    echo -e "${RED}[ERROR] Project identifier cannot be empty. Exiting.${NC}"
    exit 1
fi

PROJECT_DIR="attendance_tracker_${PROJECT_INPUT}"
ARCHIVE_NAME="attendance_tracker_${PROJECT_INPUT}_archive"

cleanup_on_interrupt() {
    echo ""
    echo -e "${YELLOW}[SIGNAL] SIGINT detected. Performing cleanup...${NC}"

    if [[ -d "$PROJECT_DIR" ]]; then
        echo -e "${YELLOW}[ARCHIVE] Bundling current state into ${ARCHIVE_NAME}.tar.gz ...${NC}"
        tar -czf "${ARCHIVE_NAME}.tar.gz" "$PROJECT_DIR" 2>/dev/null
        if [[ $? -eq 0 ]]; then
            echo -e "${GREEN}[ARCHIVE] Archive created successfully: ${ARCHIVE_NAME}.tar.gz${NC}"
        else
            echo -e "${RED}[ARCHIVE] Archive creation failed.${NC}"
        fi

        echo -e "${YELLOW}[CLEANUP] Removing incomplete directory: ${PROJECT_DIR} ...${NC}"
        rm -rf "$PROJECT_DIR"
        echo -e "${GREEN}[CLEANUP] Incomplete directory removed. Workspace is clean.${NC}"
    else
        echo -e "${YELLOW}[CLEANUP] No project directory to archive or remove.${NC}"
    fi

    echo -e "${RED}[EXIT] Script terminated by user.${NC}"
    exit 1
}

trap cleanup_on_interrupt SIGINT

if [[ -d "$PROJECT_DIR" ]]; then
    echo -e "${YELLOW}[WARNING] Directory '${PROJECT_DIR}' already exists.${NC}"
    read -rp "Overwrite it? (y/n): " OVERWRITE
    if [[ "$OVERWRITE" =~ ^[Yy]$ ]]; then
        rm -rf "$PROJECT_DIR"
        echo -e "${GREEN}[INFO] Existing directory removed.${NC}"
    else
        echo -e "${RED}[ABORT] Setup cancelled to avoid overwriting existing work.${NC}"
        exit 1
    fi
fi

echo ""
echo -e "${CYAN}[STEP 1] Creating project directory structure...${NC}"

mkdir -p "${PROJECT_DIR}/Helpers"
mkdir -p "${PROJECT_DIR}/reports"

if [[ $? -ne 0 ]]; then
    echo -e "${RED}[ERROR] Failed to create directories. Check permissions.${NC}"
    exit 1
fi
echo -e "${GREEN}[OK] Directories created.${NC}"

echo -e "${CYAN}[STEP 2] Generating project files...${NC}"

cat > "${PROJECT_DIR}/attendance_checker.py" << 'PYEOF'
import json
import csv
import os
from datetime import datetime

CONFIG_PATH  = os.path.join("Helpers", "config.json")
ASSETS_PATH  = os.path.join("Helpers", "assets.csv")
REPORTS_PATH = os.path.join("reports", "reports.log")

def load_config():
    with open(CONFIG_PATH, "r") as f:
        return json.load(f)

def load_students():
    students = []
    with open(ASSETS_PATH, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            students.append(row)
    return students

def calculate_attendance(student):
    attended  = int(student.get("classes_attended", 0))
    total     = int(student.get("total_classes", 1))
    return round((attended / total) * 100, 2) if total > 0 else 0.0

def classify(percentage, thresholds):
    if percentage >= thresholds["warning"]:
        return "Good Standing"
    elif percentage >= thresholds["failure"]:
        return "Warning"
    else:
        return "Failure"

def generate_report():
    config     = load_config()
    thresholds = config.get("thresholds", {"warning": 75, "failure": 50})
    students   = load_students()

    lines = [f"Attendance Report — {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", "=" * 50]

    for s in students:
        pct    = calculate_attendance(s)
        status = classify(pct, thresholds)
        lines.append(f"{s['name']:25s} | {pct:6.2f}% | {status}")

    lines.append("=" * 50)
    report_text = "\n".join(lines)
    print(report_text)

    os.makedirs("reports", exist_ok=True)
    with open(REPORTS_PATH, "a") as f:
        f.write(report_text + "\n\n")
    print(f"\n[INFO] Report appended to {REPORTS_PATH}")

if __name__ == "__main__":
    generate_report()
PYEOF

cat > "${PROJECT_DIR}/Helpers/assets.csv" << 'CSVEOF'
student_id,name,classes_attended,total_classes
S001,Alice Mutoni,38,40
S002,Bob Nkusi,28,40
S003,Carol Uwimana,18,40
S004,David Habimana,35,40
S005,Eve Ingabire,20,40
CSVEOF

cat > "${PROJECT_DIR}/Helpers/config.json" << 'JSONEOF'
{
  "thresholds": {
    "warning": 75,
    "failure": 50
  },
  "institution": "ALU",
  "academic_year": "2025-2026"
}
JSONEOF

cat > "${PROJECT_DIR}/reports/reports.log" << 'LOGEOF'
# Attendance Reports Log
# Generated by setup_project.sh
# Run attendance_checker.py to populate this file.
LOGEOF

echo -e "${GREEN}[OK] All project files created.${NC}"

echo ""
echo -e "${CYAN}[STEP 3] Dynamic Configuration${NC}"
echo -e "Default thresholds → Warning: ${YELLOW}75%${NC}  |  Failure: ${YELLOW}50%${NC}"
read -rp "Would you like to update the attendance thresholds? (y/n): " UPDATE_CONFIG

if [[ "$UPDATE_CONFIG" =~ ^[Yy]$ ]]; then

    while true; do
        read -rp "  Enter new Warning threshold (integer, 1-100) [default 75]: " NEW_WARNING
        NEW_WARNING="${NEW_WARNING:-75}"
        if [[ "$NEW_WARNING" =~ ^[0-9]+$ ]] && (( NEW_WARNING >= 1 && NEW_WARNING <= 100 )); then
            break
        else
            echo -e "${RED}  [ERROR] Invalid input. Please enter a whole number between 1 and 100.${NC}"
        fi
    done

    while true; do
        read -rp "  Enter new Failure threshold (integer, 1-100) [default 50]: " NEW_FAILURE
        NEW_FAILURE="${NEW_FAILURE:-50}"
        if [[ "$NEW_FAILURE" =~ ^[0-9]+$ ]] && (( NEW_FAILURE >= 1 && NEW_FAILURE <= 100 )); then
            break
        else
            echo -e "${RED}  [ERROR] Invalid input. Please enter a whole number between 1 and 100.${NC}"
        fi
    done

    if (( NEW_FAILURE >= NEW_WARNING )); then
        echo -e "${YELLOW}  [WARNING] Failure threshold is >= Warning threshold. Applying anyway.${NC}"
    fi

    CONFIG_FILE="${PROJECT_DIR}/Helpers/config.json"

    if sed --version 2>/dev/null | grep -q GNU; then
        sed -i "s/\"warning\": [0-9]*/\"warning\": ${NEW_WARNING}/" "$CONFIG_FILE"
        sed -i "s/\"failure\": [0-9]*/\"failure\": ${NEW_FAILURE}/" "$CONFIG_FILE"
    else
        sed -i '' "s/\"warning\": [0-9]*/\"warning\": ${NEW_WARNING}/" "$CONFIG_FILE"
        sed -i '' "s/\"failure\": [0-9]*/\"failure\": ${NEW_FAILURE}/" "$CONFIG_FILE"
    fi

    echo -e "${GREEN}  [OK] config.json updated → Warning: ${NEW_WARNING}%  |  Failure: ${NEW_FAILURE}%${NC}"
else
    echo -e "${CYAN}  [INFO] Keeping default thresholds (Warning: 75%, Failure: 50%).${NC}"
fi

echo ""
echo -e "${CYAN}[STEP 4] Environment Health Check${NC}"

if python3 --version &>/dev/null; then
    PY_VERSION=$(python3 --version 2>&1)
    echo -e "${GREEN}  [OK] Python3 found → ${PY_VERSION}${NC}"
else
    echo -e "${YELLOW}  [WARNING] python3 is NOT installed or not in PATH.${NC}"
    echo -e "${YELLOW}           The attendance_checker.py script will not run without it.${NC}"
fi

echo -e "${CYAN}  Verifying project structure...${NC}"
STRUCTURE_OK=true
for PATH_TO_CHECK in \
    "${PROJECT_DIR}/attendance_checker.py" \
    "${PROJECT_DIR}/Helpers/assets.csv" \
    "${PROJECT_DIR}/Helpers/config.json" \
    "${PROJECT_DIR}/reports/reports.log"; do
    if [[ -f "$PATH_TO_CHECK" ]]; then
        echo -e "${GREEN}    ✔ $PATH_TO_CHECK${NC}"
    else
        echo -e "${RED}    ✘ MISSING: $PATH_TO_CHECK${NC}"
        STRUCTURE_OK=false
    fi
done

if $STRUCTURE_OK; then
    echo -e "${GREEN}  [OK] All required files are present.${NC}"
else
    echo -e "${RED}  [WARNING] One or more files are missing. Review the output above.${NC}"
fi

echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}  Setup complete!  Project: ${PROJECT_DIR}${NC}"
echo -e "${GREEN}============================================${NC}"
echo -e "To run the tracker:  cd ${PROJECT_DIR} && python3 attendance_checker.py"
echo ""
